# .github/workflows/action-front-deploy.yml
name: Deploy
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: docker tag of the release to deploy
        type: string
        required: false
      environment:
        default: dev
        description: "Which environment would you like to deploy on ?"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: 'Insert dev domain'
        if: github.event.inputs.environment == 'dev'
        run: |
          echo "url=elements-dev.citymagine.biz" >> $GITHUB_ENV
      - name: 'Insert uat domain'
        if: github.event.inputs.environment == 'uat'
        run: |
          echo "url=elements-uat.citymagine.net" >> $GITHUB_ENV
      - name: 'Insert prod domain'
        if: github.event.inputs.environment == 'prod'
        run: |
          echo "url=elements.citymagine.com" >> $GITHUB_ENV
      - name: 'Deploy'
        uses: glopezep/helm@v1.7.1
        if: github.event.inputs.environment != 'prod'
        with:
          release: 'elements'
          namespace: '${{github.event.inputs.environment}}'
          chart: './deployment/helm'
          token: '${{ github.token }}'
          value-files: "./deployment/helm/values.yaml"
          version: ${{ github.event.inputs.release-tag }}
          values: |
            {
                "image": {
                    "tag": "${{ github.event.inputs.release-tag }}"
                },
                "environmentConfigMapName": "elements-${{github.event.inputs.environment}}-environment",
                "ingress": {
                    "hosts": [{
                        "host": "${{env.url}}"
                    }]
                }
            }
          helm: "helm3"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
      - name: 'Deploy on prod'
        uses: glopezep/helm@v1.7.1
        if: github.event.inputs.environment == 'prod'
        with:
          release: 'elements'
          namespace: '${{github.event.inputs.environment}}'
          chart: './deployment/helm'
          token: '${{ github.token }}'
          value-files: "./deployment/helm/values.yaml"
          version: ${{ github.event.inputs.release-tag }}
          values: |
            {
                "image": {
                    "tag": "${{ github.event.inputs.release-tag }}"
                },
                "environmentConfigMapName": "elements-${{github.event.inputs.environment}}-environment",
                "ingress": {
                    "hosts": [{
                        "host": "${{env.url}}"
                    }]
                }
            }
          helm: "helm3"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_PROD }}'
