# .github/workflows/action-front-deploy.yml
name: Deploy
on:
  workflow_call:
    inputs:
      release-tag:
        description: docker tag of the release to deploy
        type: string
        required: false
      environment:
        description: "Which environment would you like to deploy on ?"
        required: true
        type: string
      appname:
        description: "Name of the app. Used in URL"
        type: string
        required: true

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: 'Insert dev domain'
        if: inputs.environment == 'dev'
        run: |
          echo "url=${{inputs.appname}}-dev.citymagine.biz" >> $GITHUB_ENV
      - name: 'Insert uat domain'
        if: inputs.environment == 'uat'
        run: |
          echo "url=${{inputs.appname}}-uat.citymagine.net" >> $GITHUB_ENV
      - name: 'Insert prod domain'
        if: inputs.environment == 'prod'
        run: |
          echo "url=${{inputs.appname}}.citymagine.com" >> $GITHUB_ENV
      - name: 'Deploy'
        uses: glopezep/helm@v1.7.1
        if: inputs.environment != 'prod'
        with:
          release: '${{inputs.appname}}'
          namespace: '${{inputs.environment}}'
          chart: './deployment/helm'
          token: '${{ github.token }}'
          value-files: "./deployment/helm/values.yaml"
          version: ${{ inputs.release-tag }}
          values: |
            {
                "image": {
                    "tag": "${{ inputs.release-tag }}"
                },
                "environmentConfigMapName": "${{inputs.appname}}-${{inputs.environment}}-environment",
                "ingress": {
                    "hosts": [{
                        "host": "${{env.url}}"
                    }]
                }
            }
          helm: "helm3"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
      - name: 'Deploy on prod'
        uses: glopezep/helm@v1.7.1
        if: inputs.environment == 'prod'
        with:
          release: '${{inputs.appname}}'
          namespace: '${{inputs.environment}}'
          chart: './deployment/helm'
          token: '${{ github.token }}'
          value-files: "./deployment/helm/values.yaml"
          version: ${{ inputs.release-tag }}
          values: |
            {
                "image": {
                    "tag": "${{ inputs.release-tag }}"
                },
                "environmentConfigMapName": "${{inputs.appname}}-${{inputs.environment}}-environment",
                "ingress": {
                    "hosts": [{
                        "host": "${{env.url}}"
                    }]
                }
            }
          helm: "helm3"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_PROD }}'
