name: Make release on master
# We need a user personal access token so that CI is triggered by release
on:
  workflow_call:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Release version
        if: github.ref == 'refs/heads/master'
        run: |  
          npm i -g semantic-release @semantic-release/git @semantic-release/github @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @conveyal/maven-semantic-release
          semantic-release