name: Make release on master
# We need a user personal access token so that CI is triggered by release
on:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}
      - name: Release version
        if: github.ref == 'refs/heads/master'
        run: |
          npm ci
          node_modules/.bin/semantic-release
