name: Build & push dev image

on:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push the Docker image for dev
        if: github.ref != 'refs/heads/master'
        run: |
          docker build . -f Dockerfile -t ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:dev
          docker push ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:dev
