# .github/workflows/action-back-deploy.yml
name: Deploy
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: docker tag of the release to deploy
        type: string
        required: false
      environment:
        default: dev
        description: "Which environment would you like to deploy on ?"
        required: true
        type: choice
        options:
          - prod
          - uat
          - dev

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: 'Insert dev domain'
        if: github.event.inputs.environment == 'dev'
        run: |
          echo "url=domain-api-dev.citymagine.biz" >> $GITHUB_ENV
          echo "citymapurl=citymap-dev.citymagine.biz" >> $GITHUB_ENV
          echo "citymapperurl=citymapper-dev.citymagine.biz" >> $GITHUB_ENV
          echo "citydesignerurl=citydesigner-dev.citymagine.biz" >> $GITHUB_ENV
          echo "cityroadurl=cityroad-dev.citymagine.biz" >> $GITHUB_ENV
      - name: 'Insert uat domain'
        if: github.event.inputs.environment == 'uat'
        run: |
          echo "url=domain-api-uat.citymagine.net" >> $GITHUB_ENV
          echo "citymapurl=citymap-uat.citymagine.net" >> $GITHUB_ENV
          echo "citymapperurl=citymapper-uat.citymagine.net" >> $GITHUB_ENV
          echo "citydesignerurl=citydesigner-uat.citymagine.net" >> $GITHUB_ENV
          echo "cityroadurl=cityroad-uat.citymagine.net" >> $GITHUB_ENV
      - name: 'Insert demo domain'
        if: github.event.inputs.environment == 'demo'
        run: |
          echo "url=domain-api-demo.citymagine.com" >> $GITHUB_ENV
          echo "citymapurl=citymap-demo.citymagine.com" >> $GITHUB_ENV
          echo "citymapperurl=citymapper-demo.citymagine.com" >> $GITHUB_ENV
          echo "citydesignerurl=citydesigner-demo.citymagine.com" >> $GITHUB_ENV
          echo "cityroadurl=cityroad-demo.citymagine.com" >> $GITHUB_ENV
      - name: 'Insert prod domain'
        if: github.event.inputs.environment == 'prod'
        run: |
          echo "url=domain-api.citymagine.com" >> $GITHUB_ENV
          echo "citymapurl=citymap.citymagine.com" >> $GITHUB_ENV
          echo "citymapperurl=citymapper.citymagine.com" >> $GITHUB_ENV
          echo "citydesignerurl=citydesigner.citymagine.com" >> $GITHUB_ENV
          echo "cityroadurl=cityroad.citymagine.com" >> $GITHUB_ENV
      - name: 'Deploy'
        uses: glopezep/helm@v1.7.1
        if: github.event.inputs.environment != 'prod'
        with:
          release: 'domain-api'
          namespace: '${{github.event.inputs.environment}}'
          chart: './deployment/domain'
          token: '${{ github.token }}'
          value-files: "./deployment/domain/values.yaml"
          version: ${{ github.event.inputs.release-tag }}
          values: |
            {
                "image": {
                    "tag": "${{ github.event.inputs.release-tag }}"
                },
                "environmentConfigMapName": "domain-api-${{github.event.inputs.environment}}-environment",
                "environmentSecretName": "domain-api-${{github.event.inputs.environment}}-secret",
                "dbPasswordDev":"${{ secrets.DB_PASSWORD_DEV }}",
                "dbPasswordUat":"${{ secrets.DB_PASSWORD_UAT }}",
                "dbPasswordDemo":"${{ secrets.DB_PASSWORD_DEMO }}",
                "ingress": {
                    "hosts": [{
                        "host": "${{env.url}}"
                    }],
                    "cors": [{
                        "host": "http://localhost:4200"
                    },{
                        "host": "https://${{env.citymapurl}}"
                    },{
                        "host": "https://${{env.citymapperurl}}"
                    },{
                        "host": "https://${{env.citydesignerurl}}"
                    },{
                        "host": "https://${{env.cityroadurl}}"
                    }]
                }
            }
          helm: "helm3"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
      - name: 'Deploy on production'
        uses: glopezep/helm@v1.7.1
        if: github.event.inputs.environment == 'prod'
        with:
          release: 'domain-api'
          namespace: '${{github.event.inputs.environment}}'
          chart: './deployment/domain'
          token: '${{ github.token }}'
          value-files: "./deployment/domain/values.yaml"
          version: ${{ github.event.inputs.release-tag }}
          values: |
            {
                "image": {
                    "tag": "${{ github.event.inputs.release-tag }}"
                },
                "environmentConfigMapName": "domain-api-${{github.event.inputs.environment}}-environment",
                "environmentSecretName": "domain-api-${{github.event.inputs.environment}}-secret",
                "dbPasswordProd":"${{ secrets.DB_PASSWORD_PROD }}",
                "ingress": {
                    "hosts": [{
                        "host": "${{env.url}}"
                    }],
                    "cors": [{
                        "host": "http://localhost:4200"
                    },{
                        "host": "https://${{env.citymapurl}}"
                    },{
                        "host": "https://${{env.citymapperurl}}"
                    },{
                        "host": "https://${{env.citydesignerurl}}"
                    },{
                        "host": "https://${{env.cityroadurl}}"
                    }]
                }
            }
          helm: "helm3"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_PROD }}'
